### ISSUE TITLE
Error in linux subsystem for windows

### ISSUE THREAD

**Issue by Rashid1254** [ahernanzl/pyClim-SDM#39]
Can we run it in linux subsystem for windows ?  because I am getting these errors

"python gui_mode.py

ERROR 1: PROJ: proj_create_from_database: Open of /home/rashid/miniconda3/envs/env/share/proj failed
Synoptic domain incompatible with coordinates in input files. saf_lat_up forced from 49.0 to 46.0
Synoptic domain incompatible with coordinates in input files. saf_lat_down forced from 29.5 to 34.0
Synoptic domain incompatible with coordinates in input files. saf_lon_left forced from -18.0 to -15.0
Synoptic domain incompatible with coordinates in input files. saf_lon_right forced from 12.0 to 9.0
Traceback (most recent call last):
  File "/mnt/d/pyClim-SDM-master/pyClim-SDM-master/src/gui_mode.py", line 3441, in <module>
    main()
  File "/mnt/d/pyClim-SDM-master/pyClim-SDM-master/src/gui_mode.py", line 3438, in main
    selectionWindow()
  File "/mnt/d/pyClim-SDM-master/pyClim-SDM-master/src/gui_mode.py", line 2917, in __init__
    run, self.showWelcomeMessage = welcomeMessage().get()
  File "/mnt/d/pyClim-SDM-master/pyClim-SDM-master/src/gui_mode.py", line 175, in __init__
    root = tk.Tk()
  File "/home/rashid/miniconda3/envs/env/lib/python3.9/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable"

**Comment by ahernanzl** [comment]
Dear Rashid, 
I'm afraid pyClim-SDM is not developed for windows, sorry.
