### ISSUE TITLE
testing error

### ISSUE THREAD

**Issue by fipoucat** [ahernanzl/pyClim-SDM#45]
I am testing this useful package on mac but even though numpy installed I am getting below error:

python gui_mode.py 
Traceback (most recent call last):
  File "/Users/sarr/pyClim-SDM/src/gui_mode.py", line 36, in <module>
    from imports import *
  File "/Users/sarr/pyClim-SDM/src/../config/imports.py", line 9, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

Any hint?

**Comment by ahernanzl** [comment]
I'm sorry but the software has been designed for Linux. We do not provide support for other OS

**Comment by fipoucat** [comment]
OK, I see.

By the way, does it require a lot of cores? If not,  I'll test it on my Linux box.

**Comment by ahernanzl** [comment]
It depends on the statistical method. Machine learning methods are in general more computationally expensive than the others

**Comment by fipoucat** [comment]
I am testing on my Debian Linux but getting errors too, this time version-related; For some reason, I have python3.12

(env_pyClim-SDM) parallels@debian:~/work/pyClim-SDM/src$ python gui_mode.py
Traceback (most recent call last):
  File "/home/parallels/work/pyClim-SDM/src/gui_mode.py", line 36, in <module>
    from imports import *
  File "/home/parallels/work/pyClim-SDM/src/../config/imports.py", line 79, in <module>
    import ANA_lib
  File "/home/parallels/work/pyClim-SDM/src/../lib/ANA_lib.py", line 5, in <module>
    from advanced_settings import *
  File "/home/parallels/work/pyClim-SDM/src/../config/advanced_settings.py", line 713, in <module>
    hres_lats.update({targetVar: aux_hres_metadata[:, 2].astype(np.float)})
                                                                ^^^^^^^^
  File "/home/parallels/anaconda3/envs/env_pyClim-SDM/lib/python3.12/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?

**Comment by ahernanzl** [comment]
Hello,
Can you check your numpy version, please? It should be numpy=1.23.1. Did you follow the installation instructions?

**Comment by fipoucat** [comment]
I am using another more powerful workstation with Ubuntu 22.04 and followed install instructions but still getting error:
Executing transaction: done
(env_pyClim-SDM) sarr@ciga:~/work/pyClim-SDM/src$ python gui_mode.py 
Traceback (most recent call last):
  File "/media/sarr/DATA/work/pyClim-SDM/src/gui_mode.py", line 36, in <module>
    from imports import *
  File "/media/sarr/DATA/work/pyClim-SDM/src/../config/imports.py", line 79, in <module>
    import ANA_lib
  File "/media/sarr/DATA/work/pyClim-SDM/src/../lib/ANA_lib.py", line 5, in <module>
    from advanced_settings import *
  File "/media/sarr/DATA/work/pyClim-SDM/src/../config/advanced_settings.py", line 713, in <module>
    hres_lats.update({targetVar: aux_hres_metadata[:, 2].astype(np.float)})
  File "/home/sarr/.local/lib/python3.10/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?

**Comment by fipoucat** [comment]
corrected numpy float issue and gui displayed now.

Thank you
